version: 2

# Defining default values for all jobs
defaults: &defaults
    docker:
        - image: circleci/node:lts-browsers    

jobs:
    setup_tooling:
        <<: *defaults
        steps:
            - checkout
            # - Install npm dependencies for LWC linting and testing
            - run:
                  name: Install package dependencies
                  command: |
                      npm install
                  working_directory: ~/project/redwoods-insurance-salesforce
            - persist_to_workspace:
                  # This is an important step. If we don't store the project data (cloned GitHub source and node_modules)
                  # we'd have to re-run installation for every workflow step.
                  root: ~/
                  paths:
                      - project/*
    prettier_verify:
        # This verifies Prettier formatting
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Verify Prettier formatting
                  command: |
                      npm run prettier:verify
                  working_directory: ~/project/redwoods-insurance-salesforce
    lint_lwc:
        # This lints Lightning Web Components.
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Lint Lightning Web Components
                  command: |
                      npm run lint:lwc
                  working_directory: ~/project/redwoods-insurance-salesforce
    unit_test_lwc:
        # This unit tests Lightning Web Components.
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Unit test Lightning Web Components
                  command: |
                      npm run test:unit:coverage -- -- --runInBand
                  working_directory: ~/project/redwoods-insurance-salesforce
            - persist_to_workspace:
                  # We're saving the generated coverage results (folder 'coverage', a sub-folder to 'project') so
                  # that we can upload them in another step to Codecov.io.
                  root: ~/
                  paths:
                      - project/*
    install_cli:
        # This installs Salesforce CLI.
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Install Salesforce CLI
                  command: |
                      export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
                      export SFDX_DOMAIN_RETRY=300
                      npm install sfdx-cli
                      node_modules/sfdx-cli/bin/run --version
                      node_modules/sfdx-cli/bin/run plugins --core
            - persist_to_workspace:
                  # This is an important step. If we don't store the project data (node_modules from the CLI installation)
                  # we'd have to re-run installation for every workflow step.
                  root: ~/
                  paths:
                      - project/*
                  working_directory: ~/project/redwoods-insurance-salesforce
    lint_aura:
        # This lints Aura components.
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Lint Aura Components
                  command: |
                      npm run lint:aura
                  working_directory: ~/project/redwoods-insurance-salesforce
    setup_dx_orgs:
        # This authenticates the Dev Hub, packaging org, and creates a scratch org.
        #
        # While a scratch org isn't needed in all steps it's still part of the process. The reason for this is
        # that we need to store the sfdx configuration files for it in the workspace, so that data can be shared
        # across different workflow steps.
        #
        # Keep it simple!
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Decrypt certificate
                  command: |
                      openssl enc -nosalt -aes-256-cbc -d -in .circleci/server.key.enc -out .circleci/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            - run:
                  name: Authenticate DevHub
                  command: |
                      if [[ $CIRCLE_BRANCH == prerelease* ]]; then
                        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY_PRERELEASE --jwtkeyfile ../circleci/server.key --username $USERNAME_PRERELEASE --setdefaultdevhubusername -a HubOrg
                      else
                        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile ../.circleci/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
                      fi
                  working_directory: ~/project/redwoods-insurance-salesforce
            - run:
                  name: Define CI Org
                  # We define the to be used CI org. Based on the branch we either create a new scratch org
                  # or we use a project variable to authenticate a UAT or full-copy sandbox as target org.
                  #
                  # You can get the sfdxurl via sfdx force:org:display -u yourOrg --json --verbose from your local machine.
                  command: |
                      echo $SFDX_AUTH_PACKAGING > ~/auth.url
                      node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -s -a packagingorg -f ~/auth.url
                      node_modules/sfdx-cli/bin/run force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg -d 1
                  working_directory: ~/project/redwoods-insurance-salesforce
            - persist_to_workspace:
                  # This is an important step. If we don't store the project data (cloned GitHub source and node_modules from the CLI installation)
                  # we'd have to re-run installation for every workflow step.
                  #
                  # Also this step is crucial as we use it to share sfdx config parameters between steps.
                  root: ~/
                  paths:
                      - .sfdx/*
                      - project/*
    deploy_source:
        # This deploys the source to the ci scratch org.
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Push Source
                  command: |
                      node_modules/sfdx-cli/bin/run force:source:push -u ciorg
                  working_directory: ~/project/redwoods-insurance-salesforce
    create_and_test_package:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Create and install package
                  command: |
                      if [[ $SFDX_TEST_PACKAGING == "true" ]]; then
                        bin/packagingDeployment.sh
                      fi
                  no_output_timeout: 15m
                  working_directory: ~/project/redwoods-insurance-salesforce
    run_apex_tests:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Run Apex Tests
                  command: |
                      mkdir -p ./tests/apex
                      node_modules/sfdx-cli/bin/run force:apex:test:run -u ciorg -c -r human -d ./tests/apex -w 20
            - persist_to_workspace:
                  # This is similar to storing the coverage results from the Lightning Web Component unit test.
                  # The Apex test will store the test results in the `test` folder (which is a sub-folder of 'project')
                  # The test data will be uploaded to Codecov.io in another step.
                  root: ~/
                  paths:
                      - project/*
                  working_directory: ~/project/redwoods-insurance-salesforce
    upload_code_coverage:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Push to Codecov.io
                  command: |
                      # Uploading Apex and LWC tests
                      bash <(curl -s https://codecov.io/bash)
    cleanup_scratch_org:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Clean Up
                  command: |
                      node_modules/sfdx-cli/bin/run force:org:delete -u ciorg -p
                  working_directory: ~/project/redwoods-insurance-salesforce

workflows:
    version: 2
    build_and_test:
        jobs:
            - setup_tooling
            - prettier_verify:
                  requires:
                      - setup_tooling
                  filters:
                      branches:
                          ignore: master
            - lint_lwc:
                  requires:
                      - prettier_verify
                  filters:
                      branches:
                          ignore: master
            - install_cli:
                  requires:
                      - lint_lwc
            - setup_dx_orgs:
                  context: trailhead-global
                  requires:
                      - install_cli
            - deploy_source:
                  requires:
                      - setup_dx_orgs
            - run_apex_tests:
                  requires:
                      - deploy_source
            - cleanup_scratch_org:
                  requires:
                      - setup_dx_orgs
                      - deploy_source
